export const LL_CODES: Record<string, string[]> = {
  insertAtHead: [
    "void insertAtHead(int data){",
    "    Node* newNode = new Node(data);",
    "    if(head == NULL){",
    "        head = tail = newNode;",
    "        return;",
    "    }",
    "    newNode->next = head;",
    "    head = newNode;",
    "}"
  ],
  insertAtTail: [
    "void insertAtTail(int data){",
    "    Node* newNode = new Node(data);",
    "    if(head == NULL){",
    "        head = tail = newNode;",
    "        return;",
    "    }",
    "    tail->next = newNode;",
    "    tail = newNode;",
    "}"
  ],
  insertAtPosition: [
    "void insertAtPosition(int pos, int data){",
    "    if(pos == 1) { insertAtHead(data); return; }",
    "    Node* temp = head;",
    "    int cnt = 1;",
    "    while(cnt < pos - 1 && temp != NULL){",
    "        temp = temp->next;",
    "        cnt++;",
    "    }",
    "    if(temp == tail) { insertAtTail(data); return; }",
    "    Node* newNode = new Node(data);",
    "    newNode->next = temp->next;",
    "    temp->next = newNode;",
    "}"
  ],
  insertBeforeValue: [
    "void insertBeforeValue(int target, int data){",
    "    if(head == NULL) return;",
    "    if(head->data == target) { insertAtHead(data); return; }",
    "    Node* prev = NULL;",
    "    Node* curr = head;",
    "    while(curr != NULL && curr->data != target){",
    "        prev = curr;",
    "        curr = curr->next;",
    "    }",
    "    if(curr == NULL) return;",
    "    Node* newNode = new Node(data);",
    "    newNode->next = curr;",
    "    prev->next = newNode;",
    "}"
  ],
  insertAfterValue: [
    "void insertAfterValue(int target, int data){",
    "    Node* temp = head;",
    "    while(temp != NULL && temp->data != target){",
    "        temp = temp->next;",
    "    }",
    "    if(temp == NULL) return;",
    "    Node* newNode = new Node(data);",
    "    newNode->next = temp->next;",
    "    temp->next = newNode;",
    "    if(temp == tail) tail = newNode;",
    "}"
  ],
  insertSorted: [
    "void insertSorted(int data){",
    "    Node* newNode = new Node(data);",
    "    if(head == NULL || head->data >= data){",
    "        newNode->next = head;",
    "        head = newNode;",
    "        if(tail == NULL) tail = newNode;",
    "        return;",
    "    }",
    "    Node* curr = head;",
    "    while(curr->next != NULL && curr->next->data < data){",
    "        curr = curr->next;",
    "    }",
    "    newNode->next = curr->next;",
    "    curr->next = newNode;",
    "    if(newNode->next == NULL) tail = newNode;",
    "}"
  ],
  insertRecursive: [
    "Node* insertRecursiveUtil(Node* node, int pos, int data){",
    "    if(pos == 1 || node == NULL){",
    "        Node* newNode = new Node(data);",
    "        newNode->next = node;",
    "        return newNode;",
    "    }",
    "    node->next = insertRecursiveUtil(node->next, pos - 1, data);",
    "    return node;",
    "}",
    "void insertRecursive(int pos, int data){",
    "    head = insertRecursiveUtil(head, pos, data);",
    "    // Tail update not shown for brevity",
    "}"
  ],
  pushFront: [
    "void pushFront(int data){",
    "    Node* newNode = new Node(data);",
    "    if(head == NULL){",
    "        head = tail = newNode;",
    "        return;",
    "    }",
    "    newNode->next = head;",
    "    head = newNode;",
    "}"
  ],
  pushBack: [
    "void pushBack(int data){",
    "    Node* newNode = new Node(data);",
    "    if(head == NULL){",
    "        head = tail = newNode;",
    "        return;",
    "    }",
    "    tail->next = newNode;",
    "    tail = newNode;",
    "}"
  ],
  deleteHead: [
    "void deleteHead(){",
    "    if(head == NULL) return;",
    "    Node* temp = head;",
    "    head = head->next;",
    "    delete temp;",
    "}"
  ],
  deleteTail: [
    "void deleteTail(){",
    "    if(head == NULL) return;",
    "    if(head == tail){",
    "        delete head;",
    "        head = tail = NULL;",
    "        return;",
    "    }",
    "    Node* temp = head;",
    "    while(temp->next != tail){",
    "        temp = temp->next;",
    "    }",
    "    delete tail;",
    "    tail = temp;",
    "    tail->next = NULL;",
    "}"
  ],
  deleteByValue: [
    "void deleteByValue(int value){",
    "    if(head == NULL) return;",
    "    if(head->data == value) { deleteHead(); return; }",
    "    Node* prev = NULL;",
    "    Node* curr = head;",
    "    while(curr != NULL && curr->data != value){",
    "        prev = curr;",
    "        curr = curr->next;",
    "    }",
    "    if(curr == NULL) return;",
    "    prev->next = curr->next;",
    "    if(curr == tail) tail = prev;",
    "    delete curr;",
    "}"
  ],
  deleteAtPosition: [
    "void deleteAtPosition(int pos){",
    "    if(head == NULL || pos <= 0) return;",
    "    if(pos == 1){ deleteHead(); return; }",
    "    Node* temp = head;",
    "    for(int i=1; i<pos-1 && temp->next != NULL; ++i) temp = temp->next;",
    "    if(temp->next == NULL) return;",
    "    Node* del = temp->next;",
    "    temp->next = del->next;",
    "    if(del == tail) tail = temp;",
    "    delete del;",
    "}",
  ],
  deleteBeforeNode: [
    "void deleteBeforeNode(int target){",
    "    if(head == NULL || head->data == target) return;",
    "    Node* prev = NULL;",
    "    Node* curr = head;",
    "    while(curr->next != NULL && curr->next->data != target){",
    "        prev = curr;",
    "        curr = curr->next;",
    "    }",
    "    if(curr->next == NULL) return;",
    "    if(prev == NULL){",
    "        deleteHead();",
    "    } else {",
    "        prev->next = curr->next;",
    "        if(curr == tail) tail = prev;",
    "        delete curr;",
    "    }",
    "}",
  ],
  deleteAfterNode: [
    "void deleteAfterNode(int target){",
    "    Node* temp = head;",
    "    while(temp != NULL && temp->data != target) temp = temp->next;",
    "    if(temp == NULL || temp->next == NULL) return;",
    "    Node* del = temp->next;",
    "    temp->next = del->next;",
    "    if(del == tail) tail = temp;",
    "    delete del;",
    "}",
  ],
  deleteEntireList: [
    "void deleteEntireList(){",
    "    while(head != NULL){",
    "        Node* temp = head;",
    "        head = head->next;",
    "        delete temp;",
    "    }",
    "    tail = NULL;",
    "}",
  ],
  recursiveDelete: [
    "Node* recursiveDeleteUtil(Node* node, int target){",
    "    if(node == NULL) return NULL;",
    "    if(node->data == target){",
    "        Node* nxt = node->next;",
    "        delete node;",
    "        return recursiveDeleteUtil(nxt, target);",
    "    }",
    "    node->next = recursiveDeleteUtil(node->next, target);",
    "    return node;",
    "}",
    "void recursiveDelete(int target){",
    "    head = recursiveDeleteUtil(head, target);",
    "    Node* t = head;",
    "    tail = NULL;",
    "    while(t){ tail = t; t = t->next; }",
    "}",
  ],
  popFront: [
    "void popFront(){ deleteHead(); }"
  ],
  popBack: [
    "void popBack(){ deleteTail(); }"
  ],
  deleteNthFromEnd: [
    "void deleteNthFromEnd(int n){",
    "    Node* fast = head;",
    "    for(int i=0;i<n && fast;i++) fast = fast->next;",
    "    if(!fast){ deleteHead(); return; }",
    "    Node* slow = head;",
    "    while(fast->next){ fast = fast->next; slow = slow->next; }",
    "    Node* del = slow->next;",
    "    slow->next = del->next;",
    "    if(del == tail) tail = slow;",
    "    delete del;",
    "}",
  ],
  deleteMiddleNode: [
    "void deleteMiddleNode(){",
    "    if(head == NULL || head->next == NULL) return;",
    "    Node* slow = head;",
    "    Node* fast = head;",
    "    Node* prev = NULL;",
    "    while(fast && fast->next){",
    "        fast = fast->next->next;",
    "        prev = slow;",
    "        slow = slow->next;",
    "    }",
    "    if(prev) prev->next = slow->next;",
    "    if(slow == tail) tail = prev;",
    "    delete slow;",
    "}",
  ],
  deleteAlternateNodes: [
    "void deleteAlternateNodes(){",
    "    Node* curr = head;",
    "    while(curr && curr->next){",
    "        Node* del = curr->next;",
    "        curr->next = del->next;",
    "        if(del == tail) tail = curr;",
    "        delete del;",
    "        curr = curr->next;",
    "    }",
    "}",
  ],
  search: [
    "bool search(int key){",
    "    Node* temp = head;",
    "    while(temp != NULL){",
    "        if(temp->data == key) return true;",
    "        temp = temp->next;",
    "    }",
    "    return false;",
    "}"
  ],
  linearSearch: [
    "bool linearSearch(int key){",
    "    Node* temp = head;",
    "    while(temp != NULL){",
    "        if(temp->data == key) return true;",
    "        temp = temp->next;",
    "    }",
    "    return false;",
    "}"
  ],
  recursiveSearch: [
    "bool recursiveSearchUtil(Node* node, int key){",
    "    if(node == NULL) return false;",
    "    if(node->data == key) return true;",
    "    return recursiveSearchUtil(node->next, key);",
    "}",
    "bool recursiveSearch(int key){",
    "    return recursiveSearchUtil(head, key);",
    "}"
  ],
  searchByPosition: [
    "int searchByPosition(int pos){",
    "    if(pos <= 0) return -1;",
    "    Node* temp = head;",
    "    int currentPos = 1;",
    "    while(temp != NULL){",
    "        if(currentPos == pos) return temp->data;",
    "        temp = temp->next;",
    "        currentPos++;",
    "    }",
    "    return -1;",
    "}"
  ],
  searchLastOccurrence: [
    "int searchLastOccurrence(int key){",
    "    Node* temp = head;",
    "    int lastPos = -1;",
    "    int currentPos = 1;",
    "    while(temp != NULL){",
    "        if(temp->data == key) lastPos = currentPos;",
    "        temp = temp->next;",
    "        currentPos++;",
    "    }",
    "    return lastPos;",
    "}"
  ],
  countNodes: [
    "int countNodes(){",
    "    int cnt = 0;",
    "    Node* temp = head;",
    "    while(temp != NULL){",
    "        cnt++;",
    "        temp = temp->next;",
    "    }",
    "    return cnt;",
    "}"
  ],
  reverseIterative: [
    "void reverseIterative(){",
    "    Node* prev = NULL;",
    "    Node* curr = head;",
    "    Node* forward = NULL;",
    "    tail = head;",
    "    while(curr != NULL){",
    "        forward = curr->next;",
    "        curr->next = prev;",
    "        prev = curr;",
    "        curr = forward;",
    "    }",
    "    head = prev;",
    "}"
  ],
  middleNode: [
    "Node* middleNode(){",
    "    if(head == NULL) return NULL;",
    "    Node* slow = head;",
    "    Node* fast = head;",
    "    while(fast != NULL && fast->next != NULL){",
    "        slow = slow->next;",
    "        fast = fast->next->next;",
    "    }",
    "    return slow;",
    "}"
  ],
  detectCycle: [
    "bool detectCycle(){",
    "    Node* slow = head;",
    "    Node* fast = head;",
    "    while(fast != NULL && fast->next != NULL){",
    "        slow = slow->next;",
    "        fast = fast->next->next;",
    "        if(slow == fast) return true;",
    "    }",
    "    return false;",
    "}"
  ],
  removeDuplicates: [
    "void removeDuplicates(){",
    "    unordered_set<int> st;",
    "    Node* curr = head;",
    "    Node* prev = NULL;",
    "    while(curr != NULL){",
    "        if(st.find(curr->data) != st.end()){",
    "            prev->next = curr->next;",
    "            delete curr;",
    "            curr = prev->next;",
    "        } else {",
    "            st.insert(curr->data);",
    "            prev = curr;",
    "            curr = curr->next;",
    "        }",
    "    }",
    "}"
  ],
  isPalindrome: [
    "bool isPalindrome(){",
    "    vector<int> arr;",
    "    Node* temp = head;",
    "    while(temp != NULL){",
    "        arr.push_back(temp->data);",
    "        temp = temp->next;",
    "    }",
    "    int i = 0, j = arr.size() - 1;",
    "    while(i < j){",
    "        if(arr[i] != arr[j]) return false;",
    "        i++; j--;",
    "    }",
    "    return true;",
    "}"
  ]
};
